server.port=8761

# Eureka Server no necesita JPA ni DataSource
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Servidor Eureka no se registra a si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false

# Self-preservation off en dev/local (en prod se sobrescribe)
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Timeouts para desarrollo
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30
